lib/bugzilla_web/router.ex
defmodule BugzillaWeb.Router do
  use BugzillaWeb, :router

  import BugzillaWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug NavigationHistory.Tracker
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug BugzillaWeb.Graphql.Context
  end

  pipeline :empty_layout do
    plug :put_layout, {BugzillaWeb.LayoutView, :empty}
  end

  pipeline :auth_layout do
    plug :put_layout, {BugzillaWeb.LayoutView, :auth}
  end

  scope "/", BugzillaWeb do
    pipe_through [:browser, :empty_layout]

    get "/", ProductController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api" do
    pipe_through :api
    forward "/graph", Absinthe.Plug, schema: BugzillaWeb.Graphql.Schema
  end

  forward "/api/graphiql", Absinthe.Plug.GraphiQL, schema: BugzillaWeb.Graphql.Schema
  
  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/admin/dashboard", metrics: BugzillaWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", BugzillaWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :auth_layout]

    get "/signup", UserRegistrationController, :new
    post "/signup", UserRegistrationController, :create
    get "/signin", UserSessionController, :new
    post "/signin", UserSessionController, :create
    get "/recover", UserResetPasswordController, :new
    post "/recover", UserResetPasswordController, :create
    get "/recover/success", UserResetPasswordSuccessController, :index
    get "/signup/success", UserRegistrationSuccessController, :index
    get "/reset_password/:token", UserResetPasswordController, :edit
    put "/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", BugzillaWeb do
    pipe_through [:browser, :require_authenticated_user]

    resources "/invites", InviteController, only: [:new, :create, :show]
    get "/invites/:token/confirm", InviteController, :confirm

    resources "/projects", ProjectController, except: [:show] do
      resources "/people", PeopleController, except: [:show]

      get "/current", StoryController, :current
      get "/backlog", StoryController, :backlog
      get "/icebox", StoryController, :icebox
      get "/done", StoryController, :done

      resources "/stories", StoryController
    end

    resources "/tasks", TaskController, except: [:index, :show]
    resources "/comments", CommentController, except: [:index, :show]

    get "/dashboard", DashboardController, :index
    get "/users/settings", UserSettingsController, :edit
    delete "/users/settings", UserSettingsController, :delete
    put "/users/settings", UserSettingsController, :update
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", BugzillaWeb do
    pipe_through [:browser, :empty_layout]

    get "/privacy", PrivacyController, :index
    get "/terms", TermsController, :index
  end

  scope "/", BugzillaWeb do
    pipe_through [:browser, :auth_layout]

    delete "/logout", UserSessionController, :delete
    get "/confirm", UserConfirmationController, :new
    post "/confirm", UserConfirmationController, :create
    get "/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/bugzilla_web/views/layout_view.ex
defmodule BugzillaWeb.LayoutView do
  use BugzillaWeb, :view
end

lib/bugzilla_web/templates/layout/_email_css.html.eex
<style>
  /* -------------------------------------
      GLOBAL RESETS
  ------------------------------------- */

  /*All the styling goes here*/

  img {
    border: none;
    -ms-interpolation-mode: bicubic;
    max-width: 100%;
  }

  body {
    background-color: #f6f6f6;
    font-family: sans-serif;
    -webkit-font-smoothing: antialiased;
    font-size: 14px;
    line-height: 1.4;
    margin: 0;
    padding: 0;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
  }

  table {
    border-collapse: separate;
    mso-table-lspace: 0pt;
    mso-table-rspace: 0pt;
    width: 100%; }
    table td {
      font-family: sans-serif;
      font-size: 14px;
      vertical-align: top;
  }

  /* -------------------------------------
      BODY & CONTAINER
  ------------------------------------- */

  .body {
    background-color: #f6f6f6;
    width: 100%;
  }

  /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
  .container {
    display: block;
    margin: 0 auto !important;
    /* makes it centered */
    max-width: 580px;
    padding: 10px;
    width: 580px;
  }

  /* This should also be a block element, so that it will fill 100% of the .container */
  .content {
    box-sizing: border-box;
    display: block;
    margin: 0 auto;
    max-width: 580px;
    padding: 10px;
  }

  /* -------------------------------------
      HEADER, FOOTER, MAIN
  ------------------------------------- */
  .main {
    background: #ffffff;
    border-radius: 3px;
    width: 100%;
  }

  .wrapper {
    box-sizing: border-box;
    padding: 20px;
  }

  .content-block {
    padding-bottom: 10px;
    padding-top: 10px;
  }

  .footer {
    clear: both;
    margin-top: 10px;
    text-align: center;
    width: 100%;
  }
    .footer td,
    .footer p,
    .footer span,
    .footer a {
      color: #999999;
      font-size: 12px;
      text-align: center;
  }

  /* -------------------------------------
      TYPOGRAPHY
  ------------------------------------- */
  h1,
  h2,
  h3,
  h4 {
    color: #000000;
    font-family: sans-serif;
    font-weight: 400;
    line-height: 1.4;
    margin: 0;
    margin-bottom: 30px;
  }

  h1 {
    font-size: 35px;
    font-weight: 300;
    text-align: center;
    text-transform: capitalize;
  }

  p,
  ul,
  ol {
    font-family: sans-serif;
    font-size: 14px;
    font-weight: normal;
    margin: 0;
    margin-bottom: 15px;
  }
    p li,
    ul li,
    ol li {
      list-style-position: inside;
      margin-left: 5px;
  }

  a {
    color: #563d7c;
    text-decoration: underline;
  }

  /* -------------------------------------
      BUTTONS
  ------------------------------------- */
  .btn {
    box-sizing: border-box;
    width: 100%; }
    .btn > tbody > tr > td {
      padding-bottom: 15px; }
    .btn table {
      width: auto;
  }
    .btn table td {
      background-color: #ffffff;
      border-radius: 5px;
      text-align: center;
  }
    .btn a {
      background-color: #ffffff;
      border: solid 1px #563d7c;
      border-radius: 5px;
      box-sizing: border-box;
      color: #563d7c;
      cursor: pointer;
      display: inline-block;
      font-size: 14px;
      font-weight: bold;
      margin: 0;
      padding: 12px 25px;
      text-decoration: none;
      text-transform: capitalize;
  }

  .btn-primary table td {
    background-color: #563d7c;
  }

  .btn-primary a {
    background-color: #563d7c;
    border-color: #563d7c;
    color: #ffffff;
  }

  /* -------------------------------------
      OTHER STYLES THAT MIGHT BE USEFUL
  ------------------------------------- */
  .last {
    margin-bottom: 0;
  }

  .first {
    margin-top: 0;
  }

  .align-center {
    text-align: center;
  }

  .align-right {
    text-align: right;
  }

  .align-left {
    text-align: left;
  }

  .clear {
    clear: both;
  }

  .mt0 {
    margin-top: 0;
  }

  .mb0 {
    margin-bottom: 0;
  }

  .mb3 {
    margin-bottom: 24px;
  }

  .preheader {
    color: transparent;
    display: none;
    height: 0;
    max-height: 0;
    max-width: 0;
    opacity: 0;
    overflow: hidden;
    mso-hide: all;
    visibility: hidden;
    width: 0;
  }

  .powered-by a {
    text-decoration: none;
  }

  hr {
    border: 0;
    border-bottom: 1px solid #f6f6f6;
    margin: 20px 0;
  }

  /* -------------------------------------
      RESPONSIVE AND MOBILE FRIENDLY STYLES
  ------------------------------------- */
  @media only screen and (max-width: 620px) {
    table[class=body] h1 {
      font-size: 28px !important;
      margin-bottom: 10px !important;
    }
    table[class=body] p,
    table[class=body] ul,
    table[class=body] ol,
    table[class=body] td,
    table[class=body] span,
    table[class=body] a {
      font-size: 16px !important;
    }
    table[class=body] .wrapper,
    table[class=body] .article {
      padding: 10px !important;
    }
    table[class=body] .content {
      padding: 0 !important;
    }
    table[class=body] .container {
      padding: 0 !important;
      width: 100% !important;
    }
    table[class=body] .main {
      border-left-width: 0 !important;
      border-radius: 0 !important;
      border-right-width: 0 !important;
    }
    table[class=body] .btn table {
      width: 100% !important;
    }
    table[class=body] .btn a {
      width: 100% !important;
    }
    table[class=body] .img-responsive {
      height: auto !important;
      max-width: 100% !important;
      width: auto !important;
    }
  }

  /* -------------------------------------
      PRESERVE THESE STYLES IN THE HEAD
  ------------------------------------- */
  @media all {
    .ExternalClass {
      width: 100%;
    }
    .ExternalClass,
    .ExternalClass p,
    .ExternalClass span,
    .ExternalClass font,
    .ExternalClass td,
    .ExternalClass div {
      line-height: 100%;
    }
    .apple-link a {
      color: inherit !important;
      font-family: inherit !important;
      font-size: inherit !important;
      font-weight: inherit !important;
      line-height: inherit !important;
      text-decoration: none !important;
    }
    #MessageViewBody a {
      color: inherit;
      text-decoration: none;
      font-size: inherit;
      font-family: inherit;
      font-weight: inherit;
      line-height: inherit;
    }
    .btn-primary table td:hover {
      background-color: #34495e !important;
    }
    .btn-primary a:hover {
      background-color: #34495e !important;
      border-color: #34495e !important;
    }
  }

</style>

lib/bugzilla_web/templates/layout/email.html.eex
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= render "_email_css.html" %>
  </head>
  <body class="">
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
      <tr>
        <td>&nbsp;</td>
        <td class="container">
          <div class="content">
            <table role="presentation" class="main">
              <tr>
                <td class="wrapper">
                  <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                      <td>
                        <a href="<%= Routes.product_url(BugzillaWeb.Endpoint, :index) %>">
                          <img class="mb3" src="<%= Routes.static_url(BugzillaWeb.Endpoint, "/images/bootstrap.png") %>" width="48" height="48" />
                        </a>
                        <%= @inner_content %>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <div class="footer">
              <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block">
                    <span>If you have any questions, feedback, ideas or problems don't hesitate to contact us!</span>
                    <br>
                    <span class="apple-link"><a href="<%= Routes.user_settings_url(BugzillaWeb.Endpoint, :edit) %>">Unsubscribe</a></span>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </td>
        <td>&nbsp;</td>
      </tr>
    </table>
  </body>
</html>